apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app-service
    app: clojure-spa-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 30005
  selector:
    name: app-pod
    app: clojure-spa-app