apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app-service
    app: clojure-spa-app
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8090
      targetPort: 4000
  selector:
    name: app-pod
    app: clojure-spa-app